spring.datasource.url=jdbc:mysql://localhost:3306/product_db
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate
# Deshabilitamos ddl-auto porque usaremos Flyway para crear la tabla [cite: 21]
spring.flyway.enabled=true